#!/usr/bin/python
# coding=utf8
"""
# Author: wangbin34
# Created Time : 2020-10-18 15:23:27

# File Name: retstat.py
# Description:

"""

# OK
OK = "OK"

# namespace
ERR_NAMESPACE_IS_INVALID = "ERR_NAMESPACE_IS_INVALID"

# section
ERR_SECTION_IS_EXIST = "ERR_SECTION_IS_EXIST"
ERR_SECTION_IS_NOT_EXIST = "ERR_SECTION_IS_NOT_EXIST"
ERR_SECTION_IS_NOT_ENABLED = "ERR_SECTION_IS_NOT_ENABLED"
ERR_SECTION_IS_ENABLED = "ERR_SECTION_IS_ENABLED"
ERR_SECTION_CREATE_FAILED = "ERR_SECTION_CREATE_FAILED"
ERR_SECTION_ITEM_IS_EXIST = "ERR_SECTION_ITEM_IS_EXIST"
ERR_SECTION_ITEM_IS_NOT_EXIST = "ERR_SECTION_ITEM_IS_NOT_EXIST"
ERR_SECTION_ITEM_ADD_FAILED = "ERR_SECTION_ITEM_ADD_FAILED"
ERR_SECTION_ITEM_DELETE_FAILED = "ERR_SECTION_ITEM_DELETE_FAILED"
ERR_SECTION_ITEM_TYPE_INVALID = "ERR_SECTION_ITEM_TYPE_INVALID"
ERR_SECTION_ENABLE_FAILED = "ERR_SECTION_ENABLE_FAILED"
ERR_SECTION_DELETE_FAILED = "ERR_SECTION_DELETE_FAILED"
ERR_SECTION_NAME_IS_INVALID = "ERR_SECTION_NAME_IS_INVALID"
ERR_SECTION_VERSION_IS_INVALID = "ERR_SECTION_VERSION_IS_INVALID"

# instance
ERR_INSTANCE_IS_EXIST = "ERR_INSTANCE_IS_EXIST"
ERR_INSTANCE_IS_NOT_EXIST = "ERR_INSTANCE_IS_NOT_EXIST"
ERR_INSTANCE_IS_NOT_VALID = "ERR_INSTANCE_IS_NOT_VALID"
ERR_INSTANCE_DELETE_FAILED = "ERR_INSTANCE_DELETE_FAILED"
ERR_INSTANCE_UPDATE_FAILED = "ERR_INSTANCE_UPDATE_FAILED"
ERR_INSTANCE_NAME_IS_INVALID = "ERR_INSTANCE_NAME_IS_INVALID"

# item
ERR_ITEM_IS_EXIST = "ERR_ITEM_IS_EXIST"
ERR_ITEM_IS_NOT_EXIST = "ERR_ITEM_IS_NOT_EXIST"
ERR_ITEM_IS_NOT_FOUND = "ERR_ITEM_IS_NOT_FOUND"
ERR_ITEM_TYPE_NOT_FOUND = "ERR_ITEM_TYPE_NOT_FOUND"
ERR_ITEM_INSERT_FAILED = "ERR_ITEM_INSERT_FAILED"
ERR_ITEM_UPDATE_FAILED = "ERR_ITEM_UPDATE_FAILED"
ERR_ITEM_DELETE_FAILED = "ERR_ITEM_DELETE_FAILED"
ERR_ITEM_VALUE_OPERATOR = "ERR_ITEM_VALUE_OPERATOR"
ERR_ITEM_NAME_IS_INVALID = "ERR_ITEM_NAME_IS_INVALID"

# other
ERR_TIME_FORMATE_INVALID = "ERR_TIME_FORMATE_INVALID"
